import Link from "next/link";
import { deleteTrip } from "@/app/trips/actions";
import { deleteTransportRequest } from "@/app/requests/actions";
import { Header } from "@/components/header";
import { requireUser } from "@/lib/auth";

const date = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });

export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ message?: string; error?: string }> }) {
  const { supabase, user } = await requireUser("/dashboard");
  const { data: trips } = await supabase.from("trips").select("id, direction, departure_at, car_model, price, pet_friendly").eq("driver_id", user.id).order("departure_at");
  const { data: requests } = await supabase.from("transport_requests").select("id, direction, travel_date, preferred_time, pickup, dropoff, flexibility_type").eq("passenger_id", user.id).order("travel_date");
  const { data: memberships } = await supabase.from("conversation_members").select("conversation_id, last_read_at").eq("user_id", user.id);
  const conversationIds = memberships?.map((item) => item.conversation_id) ?? [];
  const { data: conversations } = conversationIds.length ? await supabase.from("conversations").select("id, trip_id, transport_request_id, passenger_id, updated_at, trips(driver_id, direction, departure_at), transport_requests(direction, travel_date, preferred_time)").in("id", conversationIds).order("updated_at", { ascending: false }) : { data: [] };
  const { data: allMembers } = conversationIds.length ? await supabase.from("conversation_members").select("conversation_id, user_id").in("conversation_id", conversationIds) : { data: [] };
  const otherIds = [...new Set((allMembers ?? []).filter((member) => member.user_id !== user.id).map((member) => member.user_id))];
  const { data: people } = otherIds.length ? await supabase.from("profiles").select("id, first_name").in("id", otherIds) : { data: [] };
  const { data: chatMessages } = conversationIds.length ? await supabase.from("messages").select("conversation_id, sender_id, body, created_at").in("conversation_id", conversationIds).order("created_at", { ascending: false }) : { data: [] };
  const query = await searchParams;
  return <div className="min-h-screen bg-stone-50"><Header /><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
    {(query.message || query.error) && <p className={`mb-6 rounded-xl border px-4 py-3 text-sm ${query.error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-700"}`}>{query.error ?? query.message}</p>}
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Your dashboard</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.04em] text-slate-950">Plan your journeys</h1><p className="mt-3 text-slate-500">Signed in as {user.email}</p></div><div className="flex flex-wrap gap-2"><Link href="/profile" className="focus-ring rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-600">Profile</Link><Link href="/requests/new" className="focus-ring rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-700">Post a request</Link><Link href="/trips/new" className="focus-ring rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Offer a trip</Link></div></div>
    <div className="mt-10 grid items-start gap-5 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-slate-950">I am driving...</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{trips?.length ?? 0}</span></div>
      {trips?.length ? <ul className="mt-5 space-y-3">{trips.map((trip) => <li key={trip.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-bold text-slate-900">{trip.direction === "berlin-zagreb" ? "Berlin → Zagreb" : "Zagreb → Berlin"}{trip.pet_friendly && <span className="ml-2 text-xs text-emerald-700">🐾 Pet Friendly</span>}</p><p className="mt-1 text-sm text-slate-500">{date.format(new Date(trip.departure_at))} · {trip.car_model}{trip.price ? ` · ${trip.price}` : ""}</p><div className="mt-4 flex gap-2"><Link href={`/trips/${trip.id}/edit`} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Edit</Link><form action={deleteTrip}><input type="hidden" name="id" value={trip.id} /><button className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700" type="submit">Delete</button></form></div></li>)}</ul> : <div className="mt-5 rounded-2xl border border-dashed border-slate-200 px-5 py-9 text-center"><p className="font-semibold text-slate-700">No published trips yet</p><p className="mt-1 text-sm text-slate-500">Offer your first trip when you know your travel date.</p></div>}
    </section><section className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-slate-950">I want to go...</h2><span className="rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">{requests?.length ?? 0}</span></div>
      {requests?.length ? <ul className="mt-5 space-y-3">{requests.map((request) => <li key={request.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-bold text-slate-900">{request.direction === "to-berlin" ? "To Berlin" : "From Berlin"}</p><p className="mt-1 text-sm text-slate-500">{request.pickup} → {request.dropoff}</p><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${request.travel_date}T12:00:00`))} · {request.preferred_time.slice(0, 5)}</p><div className="mt-4 flex gap-2"><Link href={`/requests/${request.id}`} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Open</Link><Link href={`/requests/${request.id}/edit`} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Edit</Link><form action={deleteTransportRequest}><input type="hidden" name="id" value={request.id} /><button className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700" type="submit">Delete</button></form></div></li>)}</ul> : <div className="mt-5 rounded-2xl border border-dashed border-slate-200 px-5 py-9 text-center"><p className="font-semibold text-slate-700">No transport requests yet</p><p className="mt-1 text-sm text-slate-500">Post a request when you need a ride.</p><Link href="/requests/new" className="mt-4 inline-flex rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Post a request</Link></div>}
    </section><section className="rounded-3xl border border-slate-200 bg-white p-6 lg:col-span-2"><div className="flex items-center justify-between"><h2 className="text-xl font-bold text-slate-950">My chats</h2><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-700">{conversations?.length ?? 0}</span></div>{conversations?.length ? <ul className="mt-5 grid gap-2 lg:grid-cols-2">{conversations.map((conversation) => { const member = allMembers?.find((item) => item.conversation_id === conversation.id && item.user_id !== user.id); const person = people?.find((item) => item.id === member?.user_id); const latest = chatMessages?.find((item) => item.conversation_id === conversation.id); const readAt = memberships?.find((item) => item.conversation_id === conversation.id)?.last_read_at; const unread = latest && latest.sender_id !== user.id && (!readAt || new Date(latest.created_at) > new Date(readAt)); const trip = conversation.trips as unknown as { direction: string; departure_at: string } | null; const request = conversation.transport_requests as unknown as { direction: string; travel_date: string; preferred_time: string } | null; const route = trip ? (trip.direction === "berlin-zagreb" ? "Berlin → Zagreb" : "Zagreb → Berlin") : (request?.direction === "from-berlin" ? "From Berlin" : "To Berlin"); const journeyWhen = trip ? date.format(new Date(trip.departure_at)) : request ? `${new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${request.travel_date}T12:00:00`))} · ${request.preferred_time.slice(0, 5)}` : "Date unavailable"; return <li key={conversation.id}><Link href={`/chat/${conversation.id}`} className="focus-ring flex items-start gap-3 rounded-2xl border border-slate-200 p-4 hover:bg-slate-50"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-700">{(person?.first_name ?? "T").slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-sm font-bold text-slate-900">{person?.first_name ?? "Traveller"}</span>{unread && <span className="size-2 rounded-full bg-blue-500" />}</span><span className="mt-0.5 block text-xs font-semibold text-slate-600">{route} · {journeyWhen}</span><span className="mt-1 block truncate text-xs text-slate-400">{latest?.body ?? "No messages yet"}</span></span>{latest && <span className="shrink-0 text-[11px] text-slate-400">{new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short" }).format(new Date(latest.created_at))}</span>}</Link></li>; })}</ul> : <div className="mt-5 rounded-2xl border border-dashed border-slate-200 px-5 py-9 text-center"><p className="font-semibold text-slate-700">No chats yet</p><p className="mt-1 text-sm text-slate-500">Open a trip or transport request to start a conversation.</p></div>}</section></div>
  </main></div>;
}
